apiVersion: v1
# 这个指的是 我 k8s 有哪些 volume
#  我 k8s 有什么？？？？
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  # 必须对应pvc里的storageClassName
  storageClassName: suibian
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
    path: "/var/lib/minikube/webook"
