apiVersion: v1
kind: Service
metadata:
  name: webook-redis
spec:
  selector:
    app: webook-redis
  ports:
    - protocol: TCP
      port: 11479 # 必须对应config/k8s.go里RedisConfig的端口
      targetPort: 6379 # 必须对应reids-deployment中的containerPort
      nodePort: 30003
  type: NodePort
