// Code generated by MockGen. DO NOT EDIT.
// Source: ./webook/internal/repository/dao/article/gorm.go
//
// Generated by this command:
//
//	mockgen -source=./webook/internal/repository/dao/article/gorm.go -package=daomocks -destination=./webook/internal/repository/dao/mocks/article.mock.go
//
// Package daomocks is a generated GoMock package.
package daomocks
